### ISSUE TITLE
Map icons appear white

### ISSUE THREAD

**Issue by waynieoaks** [JuanMTech/google_dark_theme#44]
Hi

Not sure if it is just me or something I have done wrong, but when I have the dark theme enabled and go to the map page all the icons appear white. 
![2021-03-08 18_18_48-Map - Home Assistant](https://user-images.githubusercontent.com/5962977/110363822-ef871d00-803a-11eb-8c1f-97f7fc0504f8.png)

**Comment by robertalexa** [comment]
Apart from the above, the map background is also white, whereas if you choose the Default theme, and use Dark Mode, the map is black background. This theme should follow the same approach.

**Comment by robertalexa** [comment]
Further notes on the above.

The map background is defined by the theme mode (light or dark)
See about service set_theme https://www.home-assistant.io/integrations/frontend/#defining-themes

With that being said, you can set the theme using the service while specifying the mode, and that will take care of the map.

You could also install bot Light and Dark theme from Juan and use an automation to automatically swap between them based on the sun.
```
- id: '1618771703147'
  alias: Automatic Theme Change
  description: ''
  trigger:
  - platform: state
    entity_id: sun.sun
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: "{% if is_state('sun.sun', 'above_horizon') %}\n  Google Light Theme\n\
        {% else %}\n  Google Dark Theme\n{% endif %}\n"
      mode: "{% if is_state('sun.sun', 'above_horizon') %}\n  light\n{% else %}\n\
        \  dark\n{% endif %}\n"
  mode: single
```


Hope this helps,
Rob
