### ISSUE TITLE
Text inputs and some selects are white

### ISSUE THREAD

**Issue by markgaze** [JuanMTech/google_dark_theme#46]
I've just updated to 2021.11.0 and noticed that a few of the controls are white (see below):

![image](https://user-images.githubusercontent.com/16718355/140383066-b3b13750-bd5f-4f78-962d-9b387f18d94b.png)
![image](https://user-images.githubusercontent.com/16718355/140383107-113bc795-89c9-495d-a62f-c29ef8d56d8e.png)

The class names are `mdc-select` and `mdc-text-field`. Let me know if you need any more info 🙂

**Comment by markgaze** [comment]
If anyone finds this and has the same issue, I've edited the YAML file to include the following and it looks a bit better 🙂 

```yaml
  mdc-text-field-fill-color: var(--primary-background-color)
  mdc-text-field-ink-color: var(--primary-text-color)
  mdc-text-field-label-ink-color: var(--primary-text-color
  mdc-text-field-hover-line-color: var(--primary-text-color)
  mdc-text-field-idle-line-color: var(--primary-text-color)
  mdc-select-fill-color: var(--card-background-color)
  mdc-select-hover-line-color: var(--primary-text-color)
  mdc-select-idle-line-color: var(--primary-text-color)
  mdc-select-ink-color: var(--primary-text-color)
  mdc-select-label-ink-color: var(--primary-text-color)
```
